name: Deploy to Staging

on:
  push:
    branches:
      - 'main'      # triggers on main branch for releases
      - 'feature/*' # triggers on feature branches for staging
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy to staging'
        required: true
        type: string

# Add permissions block at the workflow level
permissions:
  contents: write  # This allows the workflow to create tags

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for versioning

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set version
        id: set_version
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            # Get the latest version tag
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            
            # Remove the 'v' prefix and split into components
            VERSION_PARTS=(${LATEST_TAG#v//./ })
            MAJOR=${VERSION_PARTS[0]:-0}
            MINOR=${VERSION_PARTS[1]:-0}
            PATCH=${VERSION_PARTS[2]:-0}
            
            # Increment patch version
            PATCH=$((PATCH + 1))
            
            # Construct new version
            VERSION="${MAJOR}.${MINOR}.${PATCH}"
          else
            # For feature branches, use branch name and commit hash
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
            COMMIT_HASH=$(git rev-parse --short HEAD)
            VERSION="${BRANCH_NAME}-${COMMIT_HASH}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "New version: $VERSION"

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t go-api .
          docker tag go-api:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/go-api:${{ env.VERSION }}
          docker tag go-api:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/go-api:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/go-api:${{ env.VERSION }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/go-api:latest

      - name: Update ECS Service
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          TASK_DEFINITION: GoApiInfraStackGoApiFargateServiceTaskDef1BE268E8
          CLUSTER: GoApiInfraStack-GoApiClusterD2A0AA60-xTXIdquI0A3P
          SERVICE: GoApiInfraStack-GoApiFargateService7D208A3F-eo57UwZsRmTg
          SECRET_ARN: arn:aws:secretsmanager:us-east-1:069597727371:secret:staging/go-api-3V2g50
        run: |
          chmod +x ./.github/scripts/update_ecs.sh
          ./.github/scripts/update_ecs.sh

      - name: Create Git tag for releases
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

